# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
name: Build and deploy Python app to Azure Web App - website01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # ✅ 保持原本的 Python 3.11
      
      # ✅ **升級 `pip`、`setuptools`、`wheel`**
      - name: Manually install required dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel --no-cache-dir
          python -m pip install numpy==1.26.4 --no-cache-dir

      # ✅ 安裝 admin_service 依賴
      - name: Install dependencies for Admin Service
        run: |
          cd admin_service && pip install -r requirements.txt

      # ✅ 安裝 linebot_service 依賴（如果 `requirements.txt` 存在）
      - name: Install dependencies for Linebot Service
        run: |
          if [[ -f linebot_service/requirements.txt ]]; then
            pip install -r linebot_service/requirements.txt
          else
            echo "❌ No requirements.txt in linebot_service, skipping..."
          fi

      # ✅ 壓縮 `admin_service` 和 `linebot_service` 目錄
      - name: Zip artifact for deployment
        run: zip -r release.zip admin_service linebot_service

      # ✅ 上傳 `release.zip`
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Debug Secrets
        run: |
          echo "Client ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}"
          echo "Tenant ID: ${{ secrets.AZUREAPPSERVICE_TENANTID }}"
          echo "Subscription ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}"

      # ✅ **解壓縮 `release.zip`，確保 `app.py` 在正確位置**
      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # ✅ **設定 Azure Web App 啟動命令**
      - name: Set startup command in Azure
        run: |
          az webapp config set --resource-group YourResourceGroup \
                               --name website01 \
                               --startup-file "gunicorn -w 4 -b 0.0.0.0:8000 admin_service.app:app"

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'website01'
          slot-name: 'staging'


