# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - website01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Manually install required dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install numpy==1.26.4

      # ✅ 安裝 admin_service 依賴
      - name: Install dependencies for Admin Service
        run: |
          cd admin_service && pip install -r requirements.txt

      # ✅ 安裝 linebot_service 依賴
      - name: Install dependencies for Linebot Service
        run: |
          cd linebot_service && pip install -r requirements.txt

      # ✅ 壓縮 `admin_service` 和 `linebot_service` 目錄
      - name: Zip artifact for deployment
        run: zip -r release.zip admin_service linebot_service

      # ✅ 上傳 `release.zip`
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_60F07626EBA14309817B5C2C40DF1327 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A21B33FAAA04F6288F8C6B8530455E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C492CC725A047BBB092D5FE3940C753 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'website01'
          slot-name: 'staging'

          
